server:
  port: ${PORT:0}

spring:
  application:
    name: ms-catalog
#  profiles:
#    active: ${PROFILE:default}
#  ------ cloud parameters to exclude if local test is needed ------
#  cloud:
#    config:
#      enabled: false
  datasource:
    driverClassName: ${DDBB_USERNAME:com.mysql.cj.jdbc.Driver}
    url: ${DDBB_URL:jdbc:mysql://db.ctd.academy:3306/pi21023c01_GRUPO1}
    username: ${DDBB_USERNAME:pi21023c01_GRUPO1}
    password: ${DDBB_PASSWORD:johr9Aeb}
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true 

message: hello from ms-catalog

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.aplication.name}:${random.uuid}