server:
  port: ${PORT:8888}

spring:
  application:
    name: ms-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/arielbertotto/PI2G1-back-costume-mania
          label: Develop
          search-paths: Configuration/{application}
          force-pull: true
          clone-on-start: true
