server:
  port: ${PORT:8888}

spring:
  application:
    name: ms-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/arielbertotto/PI2G1-back-costume-mania
          default-label: PI2G1-45
          force-pull: true
          search-paths: Configuration